### ISSUE TITLE
Optional environment parameter for resource action

### ISSUE THREAD

**Issue by ZeroPointEnergy** [choria-plugins/puppet-agent#24]
As an mco/choria user I would like to deploy files directly from the Puppet Master with the resource action. This allows easy distribution of files with mco by utilizing Puppet's built in file server.

Currently, if I call the resource action with a file resource which has a source parameter, it will fail while retrieving the file from the Puppet Master, because the environment set in the Puppet Catalog object is "none", which most likely does not exist there.

The resource action should use the environment configured for the local Puppet Master by default or if provided the agent parameter.

**Comment by ripienaar** [comment]
Thanks @ZeroPointEnergy I'll need to do a bunch of testing around this to make sure other uses still work but this is great, I'll need some time to review this but will get it in for the next release

**Comment by ripienaar** [comment]
nice one @ZeroPointEnergy thanks a lot
