### ISSUE TITLE
'Compound filters are not supported' with 'runall' command

### ISSUE THREAD

**Issue by wiad** [choria-plugins/puppet-agent#38]
When using puppet6 and choria-server, the `mco puppet runall` command does not work since choria-server does not support compound filters and the runall command converts all filters to a single compound filter (happens in `find_enabled_nodes` in `util/puppetrunner.rb`).

This is a really useful command and it would be great if there was a way to make it work with choria-server.

**Comment by ripienaar** [comment]
indeed, this is the last remaining big ticket outstanding in the new choria go server.

This is tracked here https://github.com/choria-io/go-client/issues/31, I really want it, but its a giant pain in the arse :(

Will close this one and leave it open there.

thanks!
