### ISSUE TITLE
Issue with mco puppet runonce and Puppet 8

### ISSUE THREAD

**Issue by mdechiaro** [choria-plugins/puppet-agent#60]
The following error occurs when trying to run `mco puppet runonce -W fqdn=hostname.domain.com` against a Puppet 8.2.0 system. This is using the latest plugin version: `mod 'choria-mcollective_agent_puppet', '2.4.2'`

```
mco puppet runonce -W fqdn=hostname.domain.com -v
Discovering hosts using the mc method for 2 second(s) .... 1

 * [ ============================================================> ] 1 / 1


hostname.domain.com                   : Cannot clone ENV, use ENV.to_h to get a copy of ENV as a hash
    Cannot clone ENV, use ENV.to_h to get a copy of ENV as a hash

---- rpc stats ----
           Nodes: 1 / 1
     Pass / Fail: 0 / 1
      Start Time: 2023-09-22 08:28:04 -0500
  Discovery Time: 2097.48ms
      Agent Time: 1036.76ms
      Total Time: 3134.24ms
```

Let me know if there is anymore info i can provide.

**Comment by smortex** [comment]
Hey @mdechiaro 

I can't reproduce this on my personal (FreeBSD) infra and I have not yet deployed Puppet 8 on my Debian infra due to the lack of Debian 12 packages…

Can you tell us what operating-system you are using and provide the output of `puppet module list` of your Puppet Server so that we can try to find-out the culprit?

**Comment by mdechiaro** [comment]
Puppet 8 is running Ubuntu 22.04. Could this be the issue? https://github.com/choria-plugins/puppet-agent/blob/master/agent/puppet.rb#L49

Looking latest Ruby docs, `ENV.clone` will raise a type error that matches what I see. https://docs.ruby-lang.org/en/master/ENV.html#method-c-clone

**Comment by smortex** [comment]
@mdechiaro hum, that makes sense. FreeBSD default to Ruby 3.1, so I am using Puppet 8 with Ruby 3.1 and don't have this issue.  Indeed `#clone` is suspect and the suggestion form the doc to use `#to_h` instead seems totally valid.

Can you give it a try and report your findings / open a PR?  Thanks!

**Comment by mdechiaro** [comment]
@smortex  I'll take a look at this later today

**Comment by mdechiaro** [comment]
@ripienaar @smortex can we get this merge released soon? Thanks in advance!
